---
# Install a developer environment
- name: "Setup developer environment"
  hosts: localhost
  vars:
    username: ''

  tasks:
  - fail:
      msg: "username variable is not defined"
    when: username == ''

  - name: "Add user {{ username }}"
    user:
      name: "{{ username }}"
      groups: adm,cdrom,dialout,sudo,dip,floppy,plugdev,video,netdev
      append: true
      state: present

  - name: "Update apt cache"
    apt: update_cache=yes

  - name: Install apps
    apt: name={{ item }} state=latest
    with_items:
      - xorg
      - firefox-esr
      - tmux
      - i3
      - git
      - sudo
      - nfs-common
      - python3-venv
      - curl
      - podman

  - name: "clone dotfiles"
    become: yes
    become_user: "{{ username }}"
    git:
      repo: https://github.com/fnjeneza/dotfiles.git
      dest: ~{{ username }}/.dotfiles

  - name: Change owner/group of .dotfiles
    file:
      path: ~{{ username }}/.dotfiles
      owner: "{{ username }}"
      group: "{{ username }}"
      recurse: true

  - name: create links to dotfiles
    file:
      force: yes
      state: link
      src: ~{{ username }}/.dotfiles/{{item}}
      dest: ~{{ username }}/{{item}}
      owner: "{{ username }}"
      group: "{{ username }}"
    with_items:
      - .tmux.conf
      - .bashrc
      #- .vimrc
      - .Xresources
      - .profile

  - name: .vim folder shall be present
    file:
      state: directory
      path: ~{{ username }}/.vim
      owner: "{{ username }}"
      group: "{{ username }}"
      recurse: true

  - name: .local/bin folder shall be present
    file:
      state: directory
      path: ~{{ username }}/.local/bin
      owner: "{{ username }}"
      group: "{{ username }}"

  - name: .local/lib folder shall be present
    file:
      state: directory
      path: ~{{ username }}/.local/lib
      owner: "{{ username }}"
      group: "{{ username }}"

  - name: create link for coc-settings
    file:
      force: yes
      state: link
      src: ~{{ username }}/.dotfiles/coc-settings.json
      dest: ~{{ username }}/.vim/coc-settings.json
      owner: "{{ username }}"
      group: "{{ username }}"

  - name: create config directory
    file:
      state: directory
      path: ~{{ username }}/.config
      owner: "{{ username }}"
      group: "{{ username }}"

  - name: remove i3 config
    file:
      state: absent
      path: ~{{ username }}/.config/i3
      owner: "{{ username }}"
      group: "{{ username }}"

  - name: create links to dotfiles for i3 config
    file:
      force: yes
      state: link
      src: ~{{ username }}/.dotfiles/i3
      dest: ~{{ username }}/.config/i3
      owner: "{{ username }}"
      group: "{{ username }}"

  - name: build st
    shell: |
      TEMP=`mktemp -d`
      podman build -t st -f ~{{ username }}/.dotfiles/stterm/st.Containerfile $TEMP
      podman run --rm -ti -v $TEMP/local:/usr/local st
      cp -r $TEMP/local/ ~{{ username }}/.local
      

  - name: Install docker-compose
    become: yes
    become_user: "{{ username }}"
    shell: |
      curl -L --fail https://github.com/docker/compose/releases/download/1.26.2/run.sh -o ~{{ username }}/.local/bin/docker-compose
      chmod +x ~{{ username }}/.local/bin/docker-compose

  - name: Install node
    become: yes
    become_user: "{{ username }}"
    shell: curl -sL install-node.now.sh/lts | bash  -s -- --prefix ~{{ username }}/.local/ --yes

  - name: Change owner/group of .local
    file:
      path: ~{{ username }}/.local
      owner: "{{ username }}"
      group: "{{ username }}"
      recurse: true
