---
# Install a developer environment
- name: "Setup developer environment"
  hosts: localhost
  vars:
    username: ''

  tasks:
  - fail:
      msg: "username variable is not defined"
    when: username == ''

  - name: "Add user {{ username }}"
    user:
      name: "{{ username }}"
      groups: adm,cdrom,dialout,sudo,dip,floppy,plugdev,video,netdev
      append: true
      state: present

  - name: "Update apt cache"
    apt: update_cache=yes

  - name: Install apps
    apt: name={{ item }} state=latest
    with_items:
      - xorg
      - firefox-esr
      - tmux
      - i3
      - git
      - sudo
      - nfs-common

  - name: "clone dotfiles"
    become: yes
    become_user: "{{ username }}"
    git:
      repo: https://github.com/fnjeneza/dotfiles.git
      dest: ~/.dotfiles

  - name: create links to dotfiles
    become: yes
    become_user: "{{ username }}"
    file:
      force: yes
      state: link
      src: ~/.dotfiles/{{item}}
      dest: ~/{{item}}
    with_items:
      - .tmux.conf
      - .bashrc
      #- .vimrc
      - .Xresources
      - .profile

  - name: create link for coc-settings
    become: yes
    become_user: "{{ username }}"
    file:
      force: yes
      state: link
      src: ~/.dotfiles/coc-settings.json
      dest: ~/.vim/coc-settings.json

  - name: create config directory
    become: yes
    become_user: "{{ username }}"
    file:
      state: directory
      path: ~/.config

  - name: remove i3 config
    become: yes
    become_user: "{{ username }}"
    file:
      state: absent
      path: ~/.config/i3

  - name: create links to dotfiles for i3 config
    become: yes
    become_user: "{{ username }}"
    file:
      force: yes
      state: link
      src: ~/.dotfiles/i3
      dest: ~/.config/i3

  # - name: Compile and install stterm
  #   copy:
  #     src: ~/.dotfiles/stterm
  #     dest: /tmp/
