---
# Install a developer environment
- name: "Setup developer environment"
  hosts: localhost
  vars:
    user: toto

  tasks:
  - name: "Add user {{ user }}"
    user:
      name: "{{ user }}"
      groups: adm,cdrom,dialout,sudo,dip,floppy,plugdev,video,netdev 
      append: true
      state: present

  - name: "Update apt cache"
    apt: update_cache=yes

  - name: Install apps
    apt: name={{ item }} state=latest
    with_items:
      - xorg
      - firefox-esr
      - tmux
      - vim
      - i3
      - git

  - name: "clone dotfiles"
    become: yes
    become_user: "{{ user }}"
    git:
      repo: https://github.com/fnjeneza/dotfiles.git
      dest: ~/.dotfiles

  - name: create links to dotfiles
    become: yes
    become_user: "{{ user }}"
    file:
      force: yes
      state: link
      src: ~/.dotfiles/{{item}}
      dest: ~/{{item}}
    with_items:
      - .tmux.conf
      - .bashrc
      - .vimrc
      - .Xresources
      - .profile

  - name: remove i3 config
    become: yes
    become_user: "{{ user }}"
    file:
      state: absent
      path: ~/.config/i3

  - name: create links to dotfiles for i3 config
    become: yes
    become_user: "{{ user }}"
    file:
      force: yes
      state: link
      src: ~/.dotfiles/i3
      dest: ~/.config/i3

  # - name: Compile and install stterm
  #   copy:
  #     src: ~/.dotfiles/stterm
  #     dest: /tmp/

  - name: Clone Vundle git repo
    become: yes
    become_user: "{{ user }}"
    git:
      repo: https://github.com/VundleVim/Vundle.vim.git
      dest: ~/.vim/bundle/Vundle.vim

  - name: Install vim plugins
    become: yes
    become_user: "{{ user }}"
    command: "echo ' ' > vim +PluginInstall +qall"
